# Site
title: Q
description: "Site by Site"
header-img: img/home-bg.jpg
baseurl: ""
#url: "http://yourdomain.com"

# Contact
email: herrq1@zoho.com
github_username:  HerrQ
#twitter_username: xyz
#facebook_username:  xyz

# Building
markdown: redcarpet
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","serve-gollum.sh","serve-jekyll.sh"]

# Serving
host: 0.0.0.0
